export default {
  ROLE: ['SUPER_ADMIN', 'ADMIN', 'SUPER_MASTER', 'MASTER', 'USER'],
  CURRENCY: ['USD', 'INR'],
  SUPER_ADMIN: ['ADMIN', 'SUPER_MASTER', 'MASTER', 'USER'],
  ADMIN: ['SUPER_MASTER', 'MASTER', 'USER'],
  SUPER_MASTER: ['MASTER', 'USER'],
  MASTER: ['USER']
}
