# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "staging" ]

jobs:
  build:

    runs-on: staging


    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Server UP WITH Latest Code
        run: |
#          cp /home/ec2-user/.env /home/ec2-user/development/_work/eventcross-backend/eventcross-backend/.env
#          npm i --production
#          pm2 restart development
        env:
          CI: true
